namespace Common.Enums.ErrorEnums
{
	public enum ErrorCodes
	{
		SUCCESS = 0,
		INTERNAL_ERROR = 1,
		UNAUTHORIZED = 2,
		USER_DOES_NOT_EXIST = 3,
		USERNAME_AND_PASSWORD_DOESNT_MATCH = 4,
		CLAIM_DOES_NOT_EXIST = 5,
		ROLE_DOES_NOT_EXIST = 6,
		INPUT_IS_NOT_VALID = 7,
		USER_STATUS_DOES_NOT_EXIST = 8,
		GENDER_TYPE_DOES_NOT_EXIST = 9,
		CITIZEN_TYPE_DOES_NOT_EXIST = 10,
		ACCESS_DENIED = 11,
		DISCOUNT_DOES_NOT_EXIST = 12,
		VOEN_IS_EXIST = 13,
		ORGANIZATION_NAME_IS_EXIST = 14,
		ORGANIZATION_DOES_NOT_EXIST = 15,
		BRANCH_NAME_IS_EXIST = 16,
		BRANCH_DOES_NOT_EXIST = 17
	}
}
