//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string ACCESS_DENIED {
            get {
                return ResourceManager.GetString("ACCESS_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string ACCOUNT {
            get {
                return ResourceManager.GetString("ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string ACTIVE {
            get {
                return ResourceManager.GetString("ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string ADDRESS {
            get {
                return ResourceManager.GetString("ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked.
        /// </summary>
        public static string BLOCKED {
            get {
                return ResourceManager.GetString("BLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch code.
        /// </summary>
        public static string BRANCH_CODE {
            get {
                return ResourceManager.GetString("BRANCH_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch code is exist.
        /// </summary>
        public static string BRANCH_CODE_İS_EXİST {
            get {
                return ResourceManager.GetString("BRANCH_CODE_İS_EXİST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch does not exist.
        /// </summary>
        public static string BRANCH_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("BRANCH_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch is not correspond with organization.
        /// </summary>
        public static string BRANCH_IS_NOT_CORRESPOND_WITH_ORGANIZATION {
            get {
                return ResourceManager.GetString("BRANCH_IS_NOT_CORRESPOND_WITH_ORGANIZATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch name is exist.
        /// </summary>
        public static string BRANCH_NAME_IS_EXIST {
            get {
                return ResourceManager.GetString("BRANCH_NAME_IS_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot signed.
        /// </summary>
        public static string CANNOT_SIGNED {
            get {
                return ResourceManager.GetString("CANNOT_SIGNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerificate data not available.
        /// </summary>
        public static string CERTIFICATE_DATA_NOT_AVAILABLE {
            get {
                return ResourceManager.GetString("CERTIFICATE_DATA_NOT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate services is not responding.
        /// </summary>
        public static string CERTIFICATE_SERVICES_IS_NOT_RESPONDING {
            get {
                return ResourceManager.GetString("CERTIFICATE_SERVICES_IS_NOT_RESPONDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificates are not create.
        /// </summary>
        public static string CERTIFICATES_ARE_NOT_CREATE {
            get {
                return ResourceManager.GetString("CERTIFICATES_ARE_NOT_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizen type does not exist.
        /// </summary>
        public static string CITIZEN_TYPE_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("CITIZEN_TYPE_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citizenship does not exist.
        /// </summary>
        public static string CITIZENSHIP_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("CITIZENSHIP_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim does not exist.
        /// </summary>
        public static string CLAIM_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("CLAIM_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim does not exist.
        /// </summary>
        public static string CLAIM_DOES_NOT_EXIST1 {
            get {
                return ResourceManager.GetString("CLAIM_DOES_NOT_EXIST1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} and {1} do not match.
        /// </summary>
        public static string COMPARE {
            get {
                return ResourceManager.GetString("COMPARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} length can be {1}.
        /// </summary>
        public static string CONCRETE_LENGTH {
            get {
                return ResourceManager.GetString("CONCRETE_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact number.
        /// </summary>
        public static string CONTACT_NUMBER {
            get {
                return ResourceManager.GetString("CONTACT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract file does not exist.
        /// </summary>
        public static string CONTRACT_FILE_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("CONTRACT_FILE_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract file is exist.
        /// </summary>
        public static string CONTRACT_FILE_IS_EXIST {
            get {
                return ResourceManager.GetString("CONTRACT_FILE_IS_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract file type does not exist.
        /// </summary>
        public static string CONTRACT_FILE_TYPE_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("CONTRACT_FILE_TYPE_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract is not exist.
        /// </summary>
        public static string CONTRACT_IS_NOT_EXIST {
            get {
                return ResourceManager.GetString("CONTRACT_IS_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract status does not exist.
        /// </summary>
        public static string CONTRACT_STATUS_DOES_NOT_EXİST {
            get {
                return ResourceManager.GetString("CONTRACT_STATUS_DOES_NOT_EXİST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Address.
        /// </summary>
        public static string DELIVERY_ADDRESS {
            get {
                return ResourceManager.GetString("DELIVERY_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string DISCOUNT {
            get {
                return ResourceManager.GetString("DISCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount does not exist.
        /// </summary>
        public static string DISCOUNT_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("DISCOUNT_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document number.
        /// </summary>
        public static string DOCUMENT_NUMBER {
            get {
                return ResourceManager.GetString("DOCUMENT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document pin.
        /// </summary>
        public static string DOCUMENT_PİN {
            get {
                return ResourceManager.GetString("DOCUMENT_PİN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document pin is exist.
        /// </summary>
        public static string DOCUMENT_PIN_IS_EXIST {
            get {
                return ResourceManager.GetString("DOCUMENT_PIN_IS_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document type is not exist.
        /// </summary>
        public static string DOCUMENT_TYPE_IS_NOT_EXIST {
            get {
                return ResourceManager.GetString("DOCUMENT_TYPE_IS_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EMAİL {
            get {
                return ResourceManager.GetString("EMAİL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is exist.
        /// </summary>
        public static string EMAIL_IS_EXIST {
            get {
                return ResourceManager.GetString("EMAIL_IS_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email format is not valid.
        /// </summary>
        public static string EMAIL_IS_NOT_VALID {
            get {
                return ResourceManager.GetString("EMAIL_IS_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string FEMALE {
            get {
                return ResourceManager.GetString("FEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo or fingerprint can not saved.
        /// </summary>
        public static string FILE_CANNOT_SAVED {
            get {
                return ResourceManager.GetString("FILE_CANNOT_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string FILENAME {
            get {
                return ResourceManager.GetString("FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fingerprint photo was not found.
        /// </summary>
        public static string FINGERPRINT_PHOTO_WAS_NOT_FOUND {
            get {
                return ResourceManager.GetString("FINGERPRINT_PHOTO_WAS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullname.
        /// </summary>
        public static string FULLNAME {
            get {
                return ResourceManager.GetString("FULLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender type does not exist.
        /// </summary>
        public static string GENDER_TYPE_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("GENDER_TYPE_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}.
        /// </summary>
        public static string GREATER_THAN {
            get {
                return ResourceManager.GetString("GREATER_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} greater {1} than or equal to {1}.
        /// </summary>
        public static string GREATERTHANOREQUALTO {
            get {
                return ResourceManager.GetString("GREATERTHANOREQUALTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iamas data is not available.
        /// </summary>
        public static string IAMAS_DATA_IS_NOT_AVAILABLE {
            get {
                return ResourceManager.GetString("IAMAS_DATA_IS_NOT_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iamas services is not responding.
        /// </summary>
        public static string IAMAS_SERVICES_IS_NOT_RESPONDING {
            get {
                return ResourceManager.GetString("IAMAS_SERVICES_IS_NOT_RESPONDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image not found.
        /// </summary>
        public static string IMAGE_NOT_FOUND {
            get {
                return ResourceManager.GetString("IMAGE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is incorrect.
        /// </summary>
        public static string INCORRECT_PASSWORD {
            get {
                return ResourceManager.GetString("INCORRECT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error.
        /// </summary>
        public static string INTERNAL_ERROR {
            get {
                return ResourceManager.GetString("INTERNAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid.
        /// </summary>
        public static string INVALID {
            get {
                return ResourceManager.GetString("INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File count should be maximum {0}..
        /// </summary>
        public static string INVALID_FILE_COUNT {
            get {
                return ResourceManager.GetString("INVALID_FILE_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected document cannot be an edoc file..
        /// </summary>
        public static string INVALID_FILETYPE {
            get {
                return ResourceManager.GetString("INVALID_FILETYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is invalid.
        /// </summary>
        public static string INVALID_INPUT {
            get {
                return ResourceManager.GetString("INVALID_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number format is not valid.
        /// </summary>
        public static string INVALID_NUMBER_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_NUMBER_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid.
        /// </summary>
        public static string INVALID_PIN {
            get {
                return ResourceManager.GetString("INVALID_PIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid.
        /// </summary>
        public static string INVALID_PINCODE {
            get {
                return ResourceManager.GetString("INVALID_PINCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is empty.
        /// </summary>
        public static string IS_EMPTY {
            get {
                return ResourceManager.GetString("IS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be empty and must be {1}-{2} range.
        /// </summary>
        public static string IS_EMPTY_OR_UNCORRECT_LENGTH {
            get {
                return ResourceManager.GetString("IS_EMPTY_OR_UNCORRECT_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is exist.
        /// </summary>
        public static string IS_EXIST {
            get {
                return ResourceManager.GetString("IS_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not exist.
        /// </summary>
        public static string IS_NOT_EXIST {
            get {
                return ResourceManager.GetString("IS_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid.
        /// </summary>
        public static string IS_NOT_VALID {
            get {
                return ResourceManager.GetString("IS_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string IS_REQUIRED {
            get {
                return ResourceManager.GetString("IS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one character must be digit.
        /// </summary>
        public static string ISDIGIT {
            get {
                return ResourceManager.GetString("ISDIGIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} length can be {1}-{2} range.
        /// </summary>
        public static string LENGTH {
            get {
                return ResourceManager.GetString("LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than {1}.
        /// </summary>
        public static string LESS_THAN {
            get {
                return ResourceManager.GetString("LESS_THAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} less than {1} or equal to {1}.
        /// </summary>
        public static string LESSTHANOREQUALTO {
            get {
                return ResourceManager.GetString("LESSTHANOREQUALTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level is not exist.
        /// </summary>
        public static string LEVEL_IS_NOT_EXIST {
            get {
                return ResourceManager.GetString("LEVEL_IS_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one character must be lower case.
        /// </summary>
        public static string LOWERCASE {
            get {
                return ResourceManager.GetString("LOWERCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string MALE {
            get {
                return ResourceManager.GetString("MALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} maximum length can be {1}.
        /// </summary>
        public static string MAXIMUMLENGTH {
            get {
                return ResourceManager.GetString("MAXIMUMLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mime type is not multipart/form-data.
        /// </summary>
        public static string MIMETYPE_IS_NOT_MULTIPART {
            get {
                return ResourceManager.GetString("MIMETYPE_IS_NOT_MULTIPART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minimum length must be {1}.
        /// </summary>
        public static string MINIMUMLENGTH {
            get {
                return ResourceManager.GetString("MINIMUMLENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NAME {
            get {
                return ResourceManager.GetString("NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No verifcation key required.
        /// </summary>
        public static string NO_VERIFCATION_KEY_REQUIRED {
            get {
                return ResourceManager.GetString("NO_VERIFCATION_KEY_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can not be empty.
        /// </summary>
        public static string NOTEMPTY {
            get {
                return ResourceManager.GetString("NOTEMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        public static string OLD_PASSWORD {
            get {
                return ResourceManager.GetString("OLD_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation type is not exist.
        /// </summary>
        public static string OPERATION_TYPE_IS_NOT_EXIST {
            get {
                return ResourceManager.GetString("OPERATION_TYPE_IS_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization does not exist.
        /// </summary>
        public static string ORGANIZATION_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("ORGANIZATION_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization is exist.
        /// </summary>
        public static string ORGANIZATION_IS_EXIST {
            get {
                return ResourceManager.GetString("ORGANIZATION_IS_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization name is exist.
        /// </summary>
        public static string ORGANIZATION_NAME_IS_EXIST {
            get {
                return ResourceManager.GetString("ORGANIZATION_NAME_IS_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person is not exist.
        /// </summary>
        public static string PERSON_IS_NOT_EXIST {
            get {
                return ResourceManager.GetString("PERSON_IS_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo was not found.
        /// </summary>
        public static string PHOTO_WAS_NOT_FOUND {
            get {
                return ResourceManager.GetString("PHOTO_WAS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        public static string PIN {
            get {
                return ResourceManager.GetString("PIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin not exist or expired.
        /// </summary>
        public static string PIN_NOT_EXIST_OR_EXPIRED {
            get {
                return ResourceManager.GetString("PIN_NOT_EXIST_OR_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place address.
        /// </summary>
        public static string PLACE_ADDRESS {
            get {
                return ResourceManager.GetString("PLACE_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place name.
        /// </summary>
        public static string PLACE_NAME {
            get {
                return ResourceManager.GetString("PLACE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region does not exist.
        /// </summary>
        public static string REGION_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("REGION_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role does not exist.
        /// </summary>
        public static string ROLE_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("ROLE_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role does not exist.
        /// </summary>
        public static string ROLE_DOES_NOT_EXIST1 {
            get {
                return ResourceManager.GetString("ROLE_DOES_NOT_EXIST1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role group does not exist.
        /// </summary>
        public static string ROLE_GROUP_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("ROLE_GROUP_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filenames cannot be same.
        /// </summary>
        public static string SAME_FILE_NAME {
            get {
                return ResourceManager.GetString("SAME_FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is same with the an old one.
        /// </summary>
        public static string SAME_PASSWORD {
            get {
                return ResourceManager.GetString("SAME_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarif is not exist.
        /// </summary>
        public static string TARIF_IS_NOT_EXIST {
            get {
                return ResourceManager.GetString("TARIF_IS_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This person have not certificate.
        /// </summary>
        public static string THIS_PERSON_HAVE_NOT_CERTIFICATE {
            get {
                return ResourceManager.GetString("THIS_PERSON_HAVE_NOT_CERTIFICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string UNAUTHORIZED {
            get {
                return ResourceManager.GetString("UNAUTHORIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string UNAUTHORIZED1 {
            get {
                return ResourceManager.GetString("UNAUTHORIZED1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception.
        /// </summary>
        public static string UNHANDLED_EXCEPTION {
            get {
                return ResourceManager.GetString("UNHANDLED_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception.
        /// </summary>
        public static string UNHANDLED_EXCEPTION1 {
            get {
                return ResourceManager.GetString("UNHANDLED_EXCEPTION1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one characher must be upper case.
        /// </summary>
        public static string UPPERCASE {
            get {
                return ResourceManager.GetString("UPPERCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist.
        /// </summary>
        public static string USER_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("USER_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User file does not exist.
        /// </summary>
        public static string USER_FILE_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("USER_FILE_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User file is exist.
        /// </summary>
        public static string USER_FILE_IS_EXIST {
            get {
                return ResourceManager.GetString("USER_FILE_IS_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User file type does not exist.
        /// </summary>
        public static string USER_FILE_TYPE_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("USER_FILE_TYPE_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is blocked.
        /// </summary>
        public static string USER_IS_BLOCKED {
            get {
                return ResourceManager.GetString("USER_IS_BLOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not exist.
        /// </summary>
        public static string USER_IS_NOT_EXIST {
            get {
                return ResourceManager.GetString("USER_IS_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not expert or common.
        /// </summary>
        public static string USER_IS_NOT_EXPERT_OR_COMMON {
            get {
                return ResourceManager.GetString("USER_IS_NOT_EXPERT_OR_COMMON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User status does not exist.
        /// </summary>
        public static string USER_STATUS_DOES_NOT_EXIST {
            get {
                return ResourceManager.GetString("USER_STATUS_DOES_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User status is not exist.
        /// </summary>
        public static string USER_STATUS_IS_NOT_EXIST {
            get {
                return ResourceManager.GetString("USER_STATUS_IS_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string USERNAME {
            get {
                return ResourceManager.GetString("USERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and password doesn&apos;t match.
        /// </summary>
        public static string USERNAME_AND_PASSWORD_DOESNT_MATCH {
            get {
                return ResourceManager.GetString("USERNAME_AND_PASSWORD_DOESNT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and password doesn&apos;t match.
        /// </summary>
        public static string USERNAME_AND_PASSWORD_DOESNT_MATCH1 {
            get {
                return ResourceManager.GetString("USERNAME_AND_PASSWORD_DOESNT_MATCH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is exist.
        /// </summary>
        public static string USERNAME_IS_EXIST {
            get {
                return ResourceManager.GetString("USERNAME_IS_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voen.
        /// </summary>
        public static string VOEN {
            get {
                return ResourceManager.GetString("VOEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voen is exist.
        /// </summary>
        public static string VOEN_IS_EXIST {
            get {
                return ResourceManager.GetString("VOEN_IS_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voen is not exist.
        /// </summary>
        public static string VOEN_SUN_IS_NOT_EXIST {
            get {
                return ResourceManager.GetString("VOEN_SUN_IS_NOT_EXIST", resourceCulture);
            }
        }
    }
}
